### PR TITLE
better parser, allowing future extension

### PR DESCRIPTION
**Pull request by MinweiShen**
Create a new parser. This will sort of change the way to use this tool but it provides better flexibility.
For example, we can easily add '-B' for booking tickets.

Also fixed some typo.

### CODE REVIEW

**Comment by protream** [comment]
@MinweiShen 
Sorry, I can't accept this. Actually, I have considered this way at the begainning. No doubt this way will make the program more clear and extensionale, but it will damage API's simplicity. After evaluatin, I choose the latter.
I know my parser is not good. There are a lot of places to optimize. If you want to contibute, make sure DO NOT DAMAGE THE API, unless you can make it easier.

**Comment by MinweiShen** [comment]
@protream 我觉得你应该重新考虑一下。。。

**Comment by protream** [comment]
@MinweiShen 
考虑这样，带'-x' ... 选项的使用argparser解析，不带的自行解析

**Comment by MinweiShen** [comment]
@protream 这样反倒很confusing吧。照你现在的实现，输入必须按照格式，其实也行，不太灵活罢了

**Comment by yeyuguo** [comment]
还是顶 @MinweiShen , 越灵活越好，每个人的习惯不一样

**Pull request closed without merging**
